# Generated by Django 5.0.4 on 2024-04-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('year_founded', models.PositiveIntegerField()),
                ('industry', models.CharField(max_length=255)),
                ('size_range', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('linkedin_url', models.URLField()),
                ('current_employee_estimate', models.IntegerField()),
                ('total_employee_estimate', models.IntegerField()),
            ],
        ),
    ]
